# site properties and page defaults
title: Advanced Intelligent Systems
subtitle: Robotics and AI Lab
description: An easy-to-use, flexible website template for labs, with automatic citations, GitHub tag imports, pre-built components, and more.
header: /images/background_2.jpg
footer: /images/background.jpg
proofer: false

# site social media and other links
links:
  email: leejooho@is.ritsumei.ac.jp
  orcid: 0000-0003-1015-5615
  google-scholar: 71HqkKkAAAAJ&hl
  github: ais-lab
  twitter: ais_lab
  youtube: AISlabRitsumeikan
  instagram: ais_lab_rits

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-multiple-languages-plugin

languages: ["jp", "en"]
exclude_from_localizations: ["_scripts", "images", "_styles"]
default_locale_in_subfolder: true

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff